apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-lotso-documents
  labels:
    app: bridge-lotso-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-lotso-documents
  template:
    metadata:
      labels:
        app: bridge-lotso-documents
    spec:
      containers:
        - name: bridge-lotso-documents
          image: mpayalal/bridge-lotso-documents:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: RABBITMQ_USER
            value: marciano
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rabbitmq
                key: rabbitmq-password
          - name: RABBITMQ_HOST
            value: my-rabbitmq.rabbitmq-ns.svc.cluster.local
          - name: RABBITMQ_PORT
            value: "5672"
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"